apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-brilleavtale-frontend
    team: teamdigihot
  name: hm-brilleavtale-frontend
  namespace: teamdigihot
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - https://brilleavtale.intern.dev.nav.no/hjelpemidler/brilleavtale
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: false
    path: /metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 256Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
  tokenx:
    enabled: true
  env:
    - name: BRILLE_API_BASE_URL
      value: 'http://hm-brille-api.teamdigihot.svc.cluster.local'
    - name: BRILLE_API_TARGET_AUDIENCE
      value: dev-gcp:teamdigihot:hm-brille-api
    - name: GIT_COMMIT
      value: {{commit}}
  accessPolicy:
    outbound:
      rules:
        - application: hm-brille-api
        - application: nav-dekoratoren
          namespace: personbruker
