apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-brilleavtale-frontend
    team: teamdigihot
  name: hm-brilleavtale-frontend
  namespace: teamdigihot
spec:
  image: {{image}}
  team: teamdigihot
  port: 5000
  ingresses:
    - https://brilleavtale.labs.nais.io/hjelpemidler/brilleavtale
  liveness:
    path: /hjelpemidler/brilleavtale/internal/isalive
  readiness:
    path: /hjelpemidler/brilleavtale/internal/isready
  prometheus:
    enabled: true
    path: /hjelpemidler/brilleavtale/internal/metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 256Mi
  secureLogs:
    enabled: true
  env:
    - name: BRILLE_API_BASE_URL
      value: ''
    - name: BRILLE_API_TARGET_AUDIENCE
      value: ''
    - name: PORT
      value: '5000'
    - name: USE_MSW
      value: 'true'
    - name: GIT_COMMIT
      value: {{commit}}
